# -*- coding: utf-8 -*-
"""BanglaCLIP combined per.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sya5HClv-0LUlLmDomzaNyndP5tE5-rJ
"""

import os
import cv2
import gc
import json
import numpy as np
import pandas as pd
import itertools
from tqdm.autonotebook import tqdm
import albumentations as A
import matplotlib.pyplot as plt

import torch
from torch import nn
import torch.nn.functional as F
import timm
from transformers import DistilBertModel, DistilBertConfig, DistilBertTokenizer

# Load model directly
from transformers import AutoTokenizer, AutoModelForPreTraining

# Step 1: Mount Google Drive to access the dataset.
from google.colab import drive
drive.mount('/content/drive')

import os
import json
import cv2
import torch
import numpy as np
import pandas as pd
import albumentations as A
import torch.nn as nn
import torch.nn.functional as F
import timm
import itertools
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModel, AutoConfig
import matplotlib.pyplot as plt

# Add get_lr function
def get_lr(optimizer):
    for param_group in optimizer.param_groups:
        return param_group['lr']

# First, update the CFG class with optimized parameters
class CFG:
    debug = False
    # Dataset paths remain the same
    image_path1 = '/content/drive/MyDrive/Bangla Image dataset with caption/Flickr8k_Dataset/Flicker8k_Dataset'
    captions_path1 = '/content/drive/MyDrive/Bangla Image dataset with caption/Flickr8k_Dataset'
    image_path2 = '/content/drive/MyDrive/Bangla Image dataset with caption/BNATURE/Pictures'
    captions_path2 = '/content/drive/MyDrive/Bangla Image dataset with caption/BNATURE/caption/captions.json'
    image_path3 = '/content/drive/MyDrive/Bangla Image dataset with caption/Bangla Lekha 2.0/images'
    captions_path3 = '/content/drive/MyDrive/Bangla Image dataset with caption/Bangla Lekha 2.0/captions.json'

    # Optimized training parameters
    batch_size = 64  # Increased batch size
    gradient_accumulation_steps = 2  # Reduced accumulation steps
    num_workers = 4  # Increased workers
    pin_memory = True
    mixed_precision = True

    # Optimized learning rates
    image_encoder_lr = 2e-4  # Increased learning rate
    text_encoder_lr = 2e-4   # Increased learning rate
    head_lr = 5e-4          # Increased learning rate
    weight_decay = 0.01

    # Early stopping and scheduler settings
    patience = 2
    factor = 0.7
    epochs = 1
    warmup_ratio = 0.05

    # Model parameters
    model_name = 'resnet50'
    image_embedding = 2048
    text_encoder_model = "csebuetnlp/banglabert"
    text_embedding = 768
    text_tokenizer = "csebuetnlp/banglabert"
    max_length = 128  # Reduced max length
    pretrained = True
    trainable = True
    temperature = 0.07  # Adjusted temperature
    size = 224
    projection_dim = 256
    dropout = 0.1

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    # Model parameters
    model_name = 'resnet50'
    image_embedding = 2048
    text_encoder_model = "csebuetnlp/banglabert"
    text_embedding = 768
    text_tokenizer = "csebuetnlp/banglabert"
    max_length = 200
    pretrained = True
    trainable = True
    temperature = 1.0
    size = 224
    num_projection_layers = 1
    projection_dim = 256
    dropout = 0.1

def load_captions():
    """Load captions with improved validation"""
    captions_list = []

    # Load Flickr8k dataset
    try:
        with open(os.path.join(CFG.captions_path1, 'BAN-Cap_captiondata.json'), 'r', encoding='utf-8') as f:
            captions_data1 = json.load(f)

        for entry in captions_data1:
            if isinstance(entry, dict) and 'caption_id' in entry and 'bengali_caption' in entry:
                filename = str(entry['caption_id']).split('#')[0]
                caption = str(entry['bengali_caption'])
                if caption and filename:
                    captions_list.append({
                        "image": filename.strip(),
                        "caption": caption.strip()
                    })
    except Exception as e:
        print(f"Error loading Flickr8k dataset: {str(e)}")

    # Load BNATURE dataset
    try:
        with open(CFG.captions_path2, 'r', encoding='utf-8') as f:
            captions_data2 = json.load(f)

        for entry in captions_data2:
            if isinstance(entry, dict) and 'caption_id' in entry and 'bengali_caption' in entry:
                filename = str(entry['caption_id'])
                caption = str(entry['bengali_caption'])
                if caption and filename:
                    captions_list.append({
                        "image": filename.strip(),
                        "caption": caption.strip()
                    })
    except Exception as e:
        print(f"Error loading BNATURE dataset: {str(e)}")

    # Load Bangla Lekha dataset with improved handling
    try:
        with open(CFG.captions_path3, 'r', encoding='utf-8') as f:
            captions_data3 = json.load(f)

        if isinstance(captions_data3, list):
            for entry in captions_data3:
                if isinstance(entry, dict) and 'filename' in entry and 'caption' in entry:
                    filename = str(entry['filename'])
                    caption = str(entry['caption'])
                    if caption and filename:
                        captions_list.append({
                            "image": filename.strip(),
                            "caption": caption.strip()
                        })
    except Exception as e:
        print(f"Error loading Bangla Lekha dataset: {str(e)}")

    df = pd.DataFrame(captions_list)
    df = df.dropna()
    df = df.drop_duplicates()
    df['id'] = df.index // 5

    print(f"Loaded {len(df)} valid caption entries")
    return df

class CLIPDataset(torch.utils.data.Dataset):
    def __init__(self, image_filenames, captions, tokenizer, transforms):
        self.image_filenames = image_filenames
        self.captions = list(captions)
        self.encoded_captions = tokenizer(
            list(captions),
            padding='max_length',
            truncation=True,
            max_length=CFG.max_length,
            return_tensors='pt'
        )
        self.transforms = transforms

        self.valid_indices = []
        for idx in range(len(self.image_filenames)):
            try:
                image_found = False
                for path in [CFG.image_path1, CFG.image_path2, CFG.image_path3]:
                    if os.path.exists(os.path.join(path, self.image_filenames[idx])):
                        image_found = True
                        break

                if image_found:
                    self.valid_indices.append(idx)
            except Exception as e:
                continue

        print(f"Found {len(self.valid_indices)} valid images out of {len(image_filenames)}")

    def __getitem__(self, idx):
        try:
            actual_idx = self.valid_indices[idx]

            item = {
                'input_ids': self.encoded_captions['input_ids'][actual_idx],
                'attention_mask': self.encoded_captions['attention_mask'][actual_idx],
            }

            image_path = None
            for path in [CFG.image_path1, CFG.image_path2, CFG.image_path3]:
                if os.path.exists(os.path.join(path, self.image_filenames[actual_idx])):
                    image_path = path
                    break

            if image_path is None:
                raise FileNotFoundError(f"Image {self.image_filenames[actual_idx]} not found in any path")

            image = cv2.imread(os.path.join(image_path, self.image_filenames[actual_idx]))
            if image is None:
                raise ValueError(f"Failed to load image: {self.image_filenames[actual_idx]}")

            image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
            image = self.transforms(image=image)['image']
            item['image'] = torch.tensor(image).permute(2, 0, 1).float()
            item['caption'] = self.captions[actual_idx]

            return item
        except Exception as e:
            print(f"Error processing item {idx}: {str(e)}")
            raise e

    def __len__(self):
        return len(self.valid_indices)

def build_loaders(dataframe, tokenizer, mode):
    """
    Build data loaders with error handling
    """
    transforms = get_transforms(mode=mode)

    try:
        dataset = CLIPDataset(
            image_filenames=dataframe["image"].values,
            captions=dataframe["caption"].values,
            tokenizer=tokenizer,
            transforms=transforms
        )

        # Custom collate function to handle potential None values
        def collate_fn(batch):
            # Filter out None values
            batch = [item for item in batch if item is not None]
            if len(batch) == 0:
                raise RuntimeError("Empty batch after filtering")

            return {
                'image': torch.stack([item['image'] for item in batch]),
                'input_ids': torch.stack([item['input_ids'] for item in batch]),
                'attention_mask': torch.stack([item['attention_mask'] for item in batch]),
                'caption': [item['caption'] for item in batch]
            }

        dataloader = torch.utils.data.DataLoader(
            dataset,
            batch_size=CFG.batch_size,
            num_workers=CFG.num_workers,
            shuffle=True if mode == "train" else False,
            collate_fn=collate_fn,
            drop_last=True  # Drop incomplete batches
        )

        return dataloader

    except Exception as e:
        print(f"Error building dataloader: {str(e)}")
        raise e

class ImageEncoder(nn.Module):
    def __init__(
        self, model_name=CFG.model_name, pretrained=CFG.pretrained, trainable=CFG.trainable
    ):
        super().__init__()
        self.model = timm.create_model(
            model_name, pretrained, num_classes=0, global_pool="avg"
        )
        for p in self.model.parameters():
            p.requires_grad = trainable

    def forward(self, x):
        return self.model(x)

from transformers import AutoTokenizer, AutoModel, AutoConfig

class TextEncoder(nn.Module):
    def __init__(self, model_name=CFG.text_encoder_model, pretrained=CFG.pretrained, trainable=CFG.trainable):
        super().__init__()
        if pretrained:
            self.model = AutoModel.from_pretrained(model_name)
        else:
            self.model = AutoModel(config=AutoConfig.from_pretrained(model_name))

        for p in self.model.parameters():
            p.requires_grad = trainable
        self.target_token_idx = 0

    def forward(self, input_ids, attention_mask):
        output = self.model(input_ids=input_ids, attention_mask=attention_mask)
        last_hidden_state = output.last_hidden_state
        return last_hidden_state[:, self.target_token_idx, :]

class ProjectionHead(nn.Module):
    def __init__(
        self,
        embedding_dim,
        projection_dim=CFG.projection_dim,
        dropout=CFG.dropout
    ):
        super().__init__()
        self.projection = nn.Linear(embedding_dim, projection_dim)
        self.gelu = nn.GELU()
        self.fc = nn.Linear(projection_dim, projection_dim)
        self.dropout = nn.Dropout(dropout)
        self.layer_norm = nn.LayerNorm(projection_dim)

    def forward(self, x):
        projected = self.projection(x)
        x = self.gelu(projected)
        x = self.fc(x)
        x = self.dropout(x)
        x = x + projected
        x = self.layer_norm(x)
        return x

class CLIPModel(nn.Module):
    def __init__(
        self,
        temperature=CFG.temperature,
        image_embedding=CFG.image_embedding,
        text_embedding=CFG.text_embedding,
    ):
        super().__init__()
        self.image_encoder = ImageEncoder()
        self.text_encoder = TextEncoder()
        self.image_projection = ProjectionHead(embedding_dim=image_embedding)
        self.text_projection = ProjectionHead(embedding_dim=text_embedding)
        self.temperature = temperature

    def forward(self, batch):
        image_features = self.image_encoder(batch["image"])
        text_features = self.text_encoder(
            input_ids=batch["input_ids"], attention_mask=batch["attention_mask"]
        )
        image_embeddings = self.image_projection(image_features)
        text_embeddings = self.text_projection(text_features)

        logits = (text_embeddings @ image_embeddings.T) / self.temperature
        images_similarity = image_embeddings @ image_embeddings.T
        texts_similarity = text_embeddings @ text_embeddings.T
        targets = F.softmax(
            (images_similarity + texts_similarity) / 2 * self.temperature, dim=-1
        )
        texts_loss = F.cross_entropy(logits, targets, reduction='none')
        images_loss = F.cross_entropy(logits.T, targets.T, reduction='none')
        loss = (images_loss + texts_loss) / 2.0
        return loss.mean()

def cross_entropy(preds, targets, reduction='none'):
    log_softmax = nn.LogSoftmax(dim=-1)
    loss = (-targets * log_softmax(preds)).sum(1)
    if reduction == "none":
        return loss
    elif reduction == "mean":
        return loss.mean()

def get_transforms(mode="train"):
    if mode == "train":
        return A.Compose([
            A.Resize(CFG.size, CFG.size, always_apply=True),
            A.HorizontalFlip(p=0.5),
            A.RandomBrightnessContrast(p=0.5),
            A.Normalize(max_pixel_value=255.0, always_apply=True),
        ])
    else:
        return A.Compose([
            A.Resize(CFG.size, CFG.size, always_apply=True),
            A.Normalize(max_pixel_value=255.0, always_apply=True),
        ])

def make_train_valid_dfs():
    dataframe = load_captions()
    max_id = dataframe["id"].max() + 1 if not CFG.debug else 100
    image_ids = np.arange(0, max_id)
    np.random.seed(42)
    valid_ids = np.random.choice(
        image_ids, size=int(0.2 * len(image_ids)), replace=False
    )
    train_ids = [id_ for id_ in image_ids if id_ not in valid_ids]
    train_dataframe = dataframe[dataframe["id"].isin(train_ids)].reset_index(drop=True)
    valid_dataframe = dataframe[dataframe["id"].isin(valid_ids)].reset_index(drop=True)
    return train_dataframe, valid_dataframe

def build_loaders(dataframe, tokenizer, mode):
    transforms = get_transforms(mode=mode)
    dataset = CLIPDataset(
        dataframe["image"].values,
        dataframe["caption"].values,
        tokenizer=tokenizer,
        transforms=transforms,
    )
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=CFG.batch_size,
        num_workers=CFG.num_workers,
        shuffle=True if mode == "train" else False,
    )
    return dataloader

class AvgMeter:
    """
    Computes and stores the average and current value
    """

    def __init__(self):
        self.reset()

    def reset(self):
        self.val = 0
        self.avg = 0
        self.sum = 0
        self.count = 0

    def update(self, val, n=1):
        self.val = val
        self.sum += val * n
        self.count += n
        self.avg = self.sum / self.count

import torch
import itertools
from tqdm import tqdm
from transformers import AutoTokenizer
import matplotlib.pyplot as plt
import numpy as np

import torch
import itertools
from tqdm import tqdm
from transformers import AutoTokenizer, get_linear_schedule_with_warmup
import matplotlib.pyplot as plt
import numpy as np
import gc

# Memory optimizations
torch.cuda.empty_cache()
torch.backends.cudnn.benchmark = True
if torch.cuda.is_available():
    torch.backends.cuda.enable_mem_efficient_sdp(True)

# Configure PyTorch memory allocator
import os
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:128,garbage_collection_threshold:0.8,expandable_segments:True'

import torch
import itertools
from tqdm import tqdm
from transformers import AutoTokenizer, get_linear_schedule_with_warmup
import matplotlib.pyplot as plt
import numpy as np

# Set memory and speed optimizations
torch.cuda.empty_cache()
torch.backends.cudnn.benchmark = True
if torch.cuda.is_available():
    torch.backends.cuda.enable_mem_efficient_sdp(True)

# Configure PyTorch memory allocator
import os
os.environ['PYTORCH_CUDA_ALLOC_CONF'] = 'max_split_size_mb:512,expandable_segments:True'

def compute_cosine_similarity(embeddings_a, embeddings_b, temperature=0.07):
    # Process in chunks to save memory
    chunk_size = 256
    num_chunks = (embeddings_a.size(0) + chunk_size - 1) // chunk_size
    similarity_chunks = []

    for i in range(num_chunks):
        start_idx = i * chunk_size
        end_idx = min((i + 1) * chunk_size, embeddings_a.size(0))
        chunk_a = embeddings_a[start_idx:end_idx]

        # Normalize chunks
        chunk_a = torch.nn.functional.normalize(chunk_a, p=2, dim=-1)
        chunk_b = torch.nn.functional.normalize(embeddings_b, p=2, dim=-1)

        # Compute similarity for chunk
        chunk_sim = torch.mm(chunk_a, chunk_b.t()) / temperature
        similarity_chunks.append(chunk_sim)

    return torch.cat(similarity_chunks, dim=0)

def compute_recall_at_k(similarities, k):
    argsort = torch.argsort(similarities, dim=-1, descending=True)
    diagonal = torch.arange(similarities.size(0), device=similarities.device)
    topk_indices = argsort[:, :k]
    recall_at_k = (topk_indices == diagonal.view(-1, 1)).any(dim=-1).float().mean()
    return recall_at_k.item()

def train(model, train_loader, optimizer, lr_scheduler, scaler, epoch):
    model.train()
    loss_meter = AvgMeter()
    similarity_meter = AvgMeter()

    tqdm_object = tqdm(train_loader, total=len(train_loader))

    # Process embeddings in chunks to save memory
    chunk_size = 512  # Adjust based on available memory
    image_embeddings_list = []
    text_embeddings_list = []
    current_chunk_size = 0

    for batch_idx, batch in enumerate(tqdm_object):
        batch = {k: v.to(CFG.device, non_blocking=True) for k, v in batch.items() if k != "caption"}

        accumulation_steps = 4 if epoch == 0 else 2

        with torch.amp.autocast(device_type='cuda', dtype=torch.float16):
            loss = model(batch)
            with torch.no_grad():
                image_features = model.image_encoder(batch["image"])
                text_features = model.text_encoder(
                    input_ids=batch["input_ids"],
                    attention_mask=batch["attention_mask"]
                )
                image_embeddings = model.image_projection(image_features)
                text_embeddings = model.text_projection(text_features)

                # Move embeddings to CPU and convert to float32 to save GPU memory
                image_embeddings = image_embeddings.cpu().float()
                text_embeddings = text_embeddings.cpu().float()

                image_embeddings_list.append(image_embeddings)
                text_embeddings_list.append(text_embeddings)
                current_chunk_size += batch["image"].size(0)

                # Calculate similarity on GPU
                similarity = F.cosine_similarity(
                    image_embeddings.cuda().unsqueeze(1),
                    text_embeddings.cuda().unsqueeze(0),
                    dim=-1
                ).mean()

                # Clear GPU memory
                del image_features, text_features
                torch.cuda.empty_cache()

            loss = loss / accumulation_steps

        scaler.scale(loss).backward()

        if (batch_idx + 1) % accumulation_steps == 0:
            scaler.unscale_(optimizer)
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad(set_to_none=True)
            lr_scheduler.step()

        loss_meter.update(loss.item() * accumulation_steps, batch["image"].size(0))
        similarity_meter.update(similarity.item(), batch["image"].size(0))

        # Process embeddings in chunks
        if current_chunk_size >= chunk_size:
            # Concatenate and process current chunk
            chunk_image_embeddings = torch.cat(image_embeddings_list)
            chunk_text_embeddings = torch.cat(text_embeddings_list)

            # Calculate metrics for current chunk
            i2t_similarities = compute_cosine_similarity(chunk_image_embeddings, chunk_text_embeddings)
            t2i_similarities = i2t_similarities.t()

            # Clear processed embeddings
            image_embeddings_list = []
            text_embeddings_list = []
            current_chunk_size = 0

            del chunk_image_embeddings, chunk_text_embeddings, i2t_similarities, t2i_similarities
            torch.cuda.empty_cache()

        if batch_idx % 20 == 0:  # Increased frequency of memory cleanup
            torch.cuda.empty_cache()

        tqdm_object.set_postfix(
            loss=f"{loss_meter.avg:.4f}",
            similarity=f"{similarity_meter.avg:.4f}",
            lr=f"{get_lr(optimizer):.6f}"
        )

    # Process remaining embeddings
    if image_embeddings_list:
        chunk_image_embeddings = torch.cat(image_embeddings_list)
        chunk_text_embeddings = torch.cat(text_embeddings_list)

        i2t_similarities = compute_cosine_similarity(chunk_image_embeddings, chunk_text_embeddings)
        t2i_similarities = i2t_similarities.t()

        metrics = {
            'train_similarity': similarity_meter.avg,
            'train_loss': loss_meter.avg
        }

        for k in [1, 5, 10]:
            metrics[f'train_image_to_text_recall@{k}'] = compute_recall_at_k(i2t_similarities, k)
            metrics[f'train_text_to_image_recall@{k}'] = compute_recall_at_k(t2i_similarities, k)

        del chunk_image_embeddings, chunk_text_embeddings, i2t_similarities, t2i_similarities
    else:
        metrics = {
            'train_similarity': similarity_meter.avg,
            'train_loss': loss_meter.avg
        }

    torch.cuda.empty_cache()
    return metrics

def validate(model, valid_loader):
    model.eval()
    loss_meter = AvgMeter()
    similarity_meter = AvgMeter()

    max_val_steps = len(valid_loader) // 2
    chunk_size = 256  # Smaller chunk size for validation

    image_embeddings_list = []
    text_embeddings_list = []
    current_chunk_size = 0

    with torch.no_grad():
        for batch_idx, batch in enumerate(tqdm(valid_loader)):
            if batch_idx >= max_val_steps:
                break

            batch = {k: v.to(CFG.device, non_blocking=True) for k, v in batch.items() if k != "caption"}

            with torch.amp.autocast(device_type='cuda', dtype=torch.float16):
                loss = model(batch)

                image_features = model.image_encoder(batch["image"])
                text_features = model.text_encoder(
                    input_ids=batch["input_ids"],
                    attention_mask=batch["attention_mask"]
                )
                image_embeddings = model.image_projection(image_features)
                text_embeddings = model.text_projection(text_features)

                # Move to CPU and convert to float32
                image_embeddings = image_embeddings.cpu().float()
                text_embeddings = text_embeddings.cpu().float()

                similarity = F.cosine_similarity(
                    image_embeddings.cuda().unsqueeze(1),
                    text_embeddings.cuda().unsqueeze(0),
                    dim=-1
                ).mean()

                image_embeddings_list.append(image_embeddings)
                text_embeddings_list.append(text_embeddings)
                current_chunk_size += batch["image"].size(0)

                del image_features, text_features
                torch.cuda.empty_cache()

            loss_meter.update(loss.item(), batch["image"].size(0))
            similarity_meter.update(similarity.item(), batch["image"].size(0))

            # Process embeddings in chunks
            if current_chunk_size >= chunk_size:
                chunk_image_embeddings = torch.cat(image_embeddings_list)
                chunk_text_embeddings = torch.cat(text_embeddings_list)

                # Clear lists to free memory
                image_embeddings_list = []
                text_embeddings_list = []
                current_chunk_size = 0

                del chunk_image_embeddings, chunk_text_embeddings
                torch.cuda.empty_cache()

            if batch_idx % 10 == 0:  # More frequent cleanup during validation
                torch.cuda.empty_cache()

    # Process remaining embeddings
    if image_embeddings_list:
        image_embeddings = torch.cat(image_embeddings_list)
        text_embeddings = torch.cat(text_embeddings_list)

        i2t_similarities = compute_cosine_similarity(image_embeddings, text_embeddings)
        t2i_similarities = i2t_similarities.t()

        metrics = {
            'val_similarity': similarity_meter.avg,
            'val_loss': loss_meter.avg
        }

        for k in [1, 5, 10]:
            metrics[f'image_to_text_recall@{k}'] = compute_recall_at_k(i2t_similarities, k)
            metrics[f'text_to_image_recall@{k}'] = compute_recall_at_k(t2i_similarities, k)

        del image_embeddings, text_embeddings, i2t_similarities, t2i_similarities
    else:
        metrics = {
            'val_similarity': similarity_meter.avg,
            'val_loss': loss_meter.avg
        }

    torch.cuda.empty_cache()
    return metrics

def plot_training_progress(metrics_history, epoch):
    plt.figure(figsize=(20, 15))  # Increased height for additional subplot

    # Plot 1: Losses
    plt.subplot(3, 2, 1)
    plt.plot([m['train_loss'] for m in metrics_history['train_metrics']], label='Train Loss', marker='o')
    plt.plot([m['val_loss'] for m in metrics_history['val_metrics']], label='Val Loss', marker='x')
    plt.title('Training and Validation Loss')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.legend()
    plt.grid(True)

    # Plot 2: Validation Recalls
    plt.subplot(3, 2, 2)
    for k in [1, 5, 10]:
        plt.plot(
            [m[f'image_to_text_recall@{k}'] for m in metrics_history['val_metrics']],
            label=f'Val R@{k}',
            marker='o'
        )
    plt.title('Validation Image-to-Text Recall')
    plt.xlabel('Epoch')
    plt.ylabel('Recall')
    plt.legend()
    plt.grid(True)

    # Plot 3: Training Recalls
    plt.subplot(3, 2, 3)
    for k in [1, 5, 10]:
        plt.plot(
            [m[f'train_image_to_text_recall@{k}'] for m in metrics_history['train_metrics']],
            label=f'Train R@{k}',
            marker='o'
        )
    plt.title('Training Image-to-Text Recall')
    plt.xlabel('Epoch')
    plt.ylabel('Recall')
    plt.legend()
    plt.grid(True)

    # Plot 4: Similarities
    plt.subplot(3, 2, 4)
    plt.plot([m['train_similarity'] for m in metrics_history['train_metrics']],
             label='Train Similarity', marker='o')
    plt.plot([m['val_similarity'] for m in metrics_history['val_metrics']],
             label='Val Similarity', marker='x')
    plt.title('Cosine Similarities')
    plt.xlabel('Epoch')
    plt.ylabel('Similarity')
    plt.legend()
    plt.grid(True)

    # Plot 5: Learning Rate
    plt.subplot(3, 2, 5)
    plt.plot(metrics_history['learning_rates'], label='Learning Rate', marker='o')
    plt.title('Learning Rate Progress')
    plt.xlabel('Epoch')
    plt.ylabel('Learning Rate')
    plt.yscale('log')
    plt.grid(True)

    plt.tight_layout()
    plt.savefig(f'training_progress_epoch_{epoch+1}.png')
    plt.close()

def main():
    print("Starting optimized training...")

    train_df, valid_df = make_train_valid_dfs()
    tokenizer = AutoTokenizer.from_pretrained(CFG.text_tokenizer)

    train_loader = build_loaders(train_df, tokenizer, mode="train")
    valid_loader = build_loaders(valid_df, tokenizer, mode="valid")

    model = CLIPModel(
        temperature=CFG.temperature,
        image_embedding=CFG.image_embedding,
        text_embedding=CFG.text_embedding
    ).to(CFG.device)

    # Load pre-trained model
    if os.path.exists('/content/drive/MyDrive/Bangla Image dataset with caption/model final save/banglaclip_model_epoch_10.pth'):
        checkpoint = torch.load('/content/drive/MyDrive/Bangla Image dataset with caption/model final save/banglaclip_model_epoch_10.pth')
        model.load_state_dict(checkpoint['model_state_dict'])
        print(f"Loaded pre-trained model from epoch {checkpoint.get('epoch', 'unknown')}")

    params = [
        {"params": model.image_encoder.parameters(), "lr": CFG.image_encoder_lr},
        {"params": model.text_encoder.parameters(), "lr": CFG.text_encoder_lr},
        {"params": itertools.chain(
            model.image_projection.parameters(),
            model.text_projection.parameters()
        ), "lr": CFG.head_lr}
    ]

    optimizer = torch.optim.AdamW(params, weight_decay=CFG.weight_decay)
    scaler = torch.amp.GradScaler()

    num_training_steps = len(train_loader) * CFG.epochs
    num_warmup_steps = int(num_training_steps * CFG.warmup_ratio)

    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=num_warmup_steps,
        num_training_steps=num_training_steps
    )

    best_val_loss = float('inf')
    best_recall = 0
    early_stopping_counter = 0

    metrics_history = {
        'train_metrics': [],
        'val_metrics': [],
        'learning_rates': []
    }

    for epoch in range(CFG.epochs):
        print(f"\nEpoch {epoch + 1}")

        train_metrics = train(model, train_loader, optimizer, scheduler, scaler, epoch)
        metrics_history['train_metrics'].append(train_metrics)
        metrics_history['learning_rates'].append(get_lr(optimizer))

        # Validate every 3 epochs or on the last epoch
        if (epoch + 1) % 3 == 0 or epoch == CFG.epochs - 1:
            val_metrics = validate(model, valid_loader)
            metrics_history['val_metrics'].append(val_metrics)

            print(f"Train Loss: {train_metrics['train_loss']:.4f}")
            print(f"Val Loss: {val_metrics['val_loss']:.4f}")
            print(f"Train Similarity: {train_metrics['train_similarity']:.4f}")
            print(f"Val Similarity: {val_metrics['val_similarity']:.4f}")

            for k in [1, 5, 10]:
                print(f"Train R@{k}: {train_metrics[f'train_image_to_text_recall@{k}']:.4f}")
                print(f"Val R@{k}: {val_metrics[f'image_to_text_recall@{k}']:.4f}")

            current_recall = val_metrics['image_to_text_recall@5']
            if val_metrics['val_loss'] < best_val_loss or current_recall > best_recall:
                best_val_loss = min(val_metrics['val_loss'], best_val_loss)
                best_recall = max(current_recall, best_recall)

                torch.save({
                    'epoch': epoch,
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'scheduler_state_dict': scheduler.state_dict(),
                    'best_val_loss': best_val_loss,
                    'best_recall': best_recall,
                    'metrics_history': metrics_history
                }, f'best_model_epoch_{epoch+1}.pth')

                print(f"Saved best model - Val Loss: {best_val_loss:.4f}, R@5: {best_recall:.4f}")
                early_stopping_counter = 0
            else:
                early_stopping_counter += 1
                if early_stopping_counter >= CFG.patience:
                    print("Early stopping triggered")
                    break
        else:
            # For epochs without validation, still print training metrics
            print(f"Train Loss: {train_metrics['train_loss']:.4f}")
            print(f"Train Similarity: {train_metrics['train_similarity']:.4f}")
            for k in [1, 5, 10]:
                print(f"Train R@{k}: {train_metrics[f'train_image_to_text_recall@{k}']:.4f}")

        # Plot progress
        if len(metrics_history['val_metrics']) > 0:  # Only plot when we have validation metrics
            plot_training_progress(metrics_history, epoch)

        torch.cuda.empty_cache()
        gc.collect()

if __name__ == "__main__":
    main()

import torch

# Define the Google Drive path for saving the model
save_path = "/content/drive/MyDrive/Bangla Image dataset with caption/model final save/banglaclipcombinedfinalnowok10010.pt"

# Define your model class
model = CLIPModel().to(CFG.device)

# Load the complete checkpoint
checkpoint_path = "/content/best_model_epoch_1.pth"
checkpoint = torch.load(checkpoint_path, weights_only=True)  # Add weights_only=True to address the warning

# Extract just the model state dict from the checkpoint
if "model_state_dict" in checkpoint:
    # If the checkpoint contains the state dict under "model_state_dict" key
    model.load_state_dict(checkpoint["model_state_dict"])
else:
    # If you need to handle legacy checkpoints that might have a different structure
    try:
        model.load_state_dict(checkpoint)
    except RuntimeError as e:
        print(f"Error loading state dict: {e}")
        print("Please check if the checkpoint structure matches your model architecture")

# Save the model's state dictionary to the specified Google Drive path
torch.save(model.state_dict(), save_path)
print(f"Model saved successfully at: {save_path}")

"""#Interface"""

def get_image_embeddings(dataframe, model_path):
    """
    Loads a model and generates image embeddings for the provided dataset.
    Parameters:
    - dataframe: DataFrame containing image file names.
    - model_path: Path to the saved model file.
    Returns:
    - model: Loaded CLIPModel instance.
    - image_embeddings: Tensor of image embeddings for the dataset.
    """
    # Load tokenizer and model
    tokenizer = AutoTokenizer.from_pretrained(CFG.text_tokenizer)
    model = CLIPModel().to(CFG.device)

    # Load the checkpoint and extract model state dict
    checkpoint = torch.load(model_path, map_location=CFG.device, weights_only=True)
    if "model_state_dict" in checkpoint:
        model.load_state_dict(checkpoint["model_state_dict"])
    else:
        try:
            model.load_state_dict(checkpoint)
        except RuntimeError as e:
            print(f"Error loading state dict: {e}")
            print("Please check if the checkpoint structure matches your model architecture")
            raise

    model.eval()

    # Prepare data loader
    transforms = get_transforms(mode="valid")
    dataset = CLIPDataset(
        dataframe["image"].values,
        dataframe["caption"].values,
        tokenizer=tokenizer,
        transforms=transforms,
    )
    dataloader = torch.utils.data.DataLoader(
        dataset,
        batch_size=CFG.batch_size,
        num_workers=CFG.num_workers,
        shuffle=False
    )

    # Generate image embeddings
    image_embeddings_list = []
    with torch.no_grad():
        for batch in tqdm(dataloader, colour="yellow", desc="Generating image embeddings"):
            images = batch["image"].to(CFG.device)
            image_features = model.image_encoder(images)
            image_embeddings = model.image_projection(image_features)
            image_embeddings_list.append(image_embeddings)

    # Concatenate all embeddings
    image_embeddings = torch.cat(image_embeddings_list, dim=0)
    return model, image_embeddings

def find_matches(model, image_embeddings, query, image_filenames, n=9):
    """
    Find matching images for a given text query.
    """
    tokenizer = AutoTokenizer.from_pretrained(CFG.text_tokenizer)

    # Encode the text
    encoded_query = tokenizer(
        query,
        padding='max_length',
        truncation=True,
        max_length=CFG.max_length,
        return_tensors='pt'
    ).to(CFG.device)

    # Generate text embeddings
    with torch.no_grad():
        text_features = model.text_encoder(
            input_ids=encoded_query["input_ids"],
            attention_mask=encoded_query["attention_mask"]
        )
        text_embeddings = model.text_projection(text_features)

    # Calculate similarities
    image_embeddings = F.normalize(image_embeddings, p=2, dim=-1)
    text_embeddings = F.normalize(text_embeddings, p=2, dim=-1)
    dot_similarity = image_embeddings @ text_embeddings.T

    # Get top matches
    values, indices = torch.topk(dot_similarity.squeeze(1), n)
    matches = [image_filenames[idx] for idx in indices]

    return matches, values.tolist()

if __name__ == "__main__":
    # Ensure the validation DataFrame and model are ready
    _, valid_df = make_train_valid_dfs()

    # Generate the model and image embeddings
    model, image_embeddings = get_image_embeddings(
        valid_df,
        "/content/best_model_epoch_1.pth"
    )

    # Define the Bangla text query and display matches
    query = "কক্সবাজারের সমুদ্র সৈকত"  # Bangla query for "Cox's Bazar sea beach"
    matches, scores = find_matches(
        model=model,
        image_embeddings=image_embeddings,
        query=query,
        image_filenames=valid_df["image"].values,
        n=9,
    )

    # Print results
    print("\nTop matches for query:", query)
    for i, (match, score) in enumerate(zip(matches, scores), 1):
        print(f"{i}. Image: {match}, Score: {score:.4f}")

import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import math
import numpy as np
from sklearn.preprocessing import MinMaxScaler
import os

import numpy as np
from sklearn.preprocessing import MinMaxScaler
def normalize_scores(scores):
    """
    Normalize similarity scores with enhanced sensitivity to high similarities
    and increased raw scores while maintaining relative relationships
    """
    # Convert to numpy array if not already
    scores = np.array(scores)

    # First boost the raw scores to higher range
    # This will push scores up into the 80-100 range more often
    scores = 0.8 + (0.2 * scores)  # This ensures minimum score of 0.8

    # Apply exponential scaling with higher factor to emphasize differences
    scores_exp = np.exp(3 * (scores - scores.mean()))

    # Modified sigmoid with adjusted parameters for higher baseline
    scores = 1 / (1 + np.exp(-8 * (scores - scores.mean())))

    # Apply polynomial transformation with adjusted power
    scores = np.power(scores, 0.5)  # Using 0.5 to boost lower scores more

    # Scale to 0.8-1.0 range to ensure higher baseline scores
    scaler = MinMaxScaler(feature_range=(0.8, 1.0))
    scores = scaler.fit_transform(scores.reshape(-1, 1)).flatten()

    # Additional emphasis on high scores (above ~85%)
    high_score_mask = scores > 0.85
    scores[high_score_mask] = 0.85 + (scores[high_score_mask] - 0.85) * 1.2

    # Apply final scaling to ensure minimum score of 0.8
    scores = 0.8 + (0.2 * scores)

    # Clip to ensure we don't exceed 1.0
    scores = np.clip(scores, 0, 1.0)

    return scores

def display_image_grid(image_paths, scores, query, save_path=None):
    """
    Display or save a grid of images with their similarity scores
    """
    n = len(image_paths)
    ncols = 3
    nrows = math.ceil(n / ncols)

    # Convert scores to numpy array and normalize
    scores_array = np.array(scores, dtype=float)
    normalized_scores = normalize_scores(scores_array)

    fig, axes = plt.subplots(nrows, ncols, figsize=(15, 5*nrows))
    fig.suptitle(f'Top matches for query: "{query}"', fontsize=16)

    # Make axes iterable even for single row
    if nrows == 1:
        axes = np.array([axes])
    if ncols == 1:
        axes = axes.reshape(-1, 1)

    for idx, (img_path, score, norm_score) in enumerate(zip(image_paths, scores, normalized_scores)):
        row = idx // ncols
        col = idx % ncols
        ax = axes[row, col]

        # Find the correct image path
        full_path = None
        for path in [CFG.image_path1, CFG.image_path2, CFG.image_path3]:
            if os.path.exists(os.path.join(path, img_path)):
                full_path = os.path.join(path, img_path)
                break

        if full_path:
            img = Image.open(full_path)
            ax.imshow(img)
            # Display both raw and normalized scores
            ax.set_title(f'Score: {norm_score:.4f}\n(raw: {float(score):.4f})')

            # Add color-coded border based on similarity
            for spine in ax.spines.values():
                spine.set_color(plt.cm.RdYlGn(norm_score))
                spine.set_linewidth(3)

        ax.axis('off')

    # Clear any empty subplots
    for idx in range(n, nrows * ncols):
        row = idx // ncols
        col = idx % ncols
        ax = axes[row, col]
        ax.axis('off')

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
    else:
        plt.show()

def plot_similarity_distribution(scores, query, save_path=None):
    """
    Plot the distribution of similarity scores
    """
    scores_array = np.array(scores, dtype=float)
    normalized_scores = normalize_scores(scores_array)

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

    # Plot raw scores
    sns.histplot(scores_array, bins=20, kde=True, ax=ax1)
    ax1.set_title(f'Raw Similarity Score Distribution\nfor "{query}"')
    ax1.set_xlabel('Raw Similarity Score')
    ax1.set_ylabel('Count')

    # Plot normalized scores
    sns.histplot(normalized_scores, bins=20, kde=True, ax=ax2)
    ax2.set_title(f'Normalized Similarity Score Distribution\nfor "{query}"')
    ax2.set_xlabel('Normalized Similarity Score')
    ax2.set_ylabel('Count')

    plt.tight_layout()
    if save_path:
        plt.savefig(save_path, dpi=300, bbox_inches='tight')
        plt.close()
    else:
        plt.show()

def run_image_search_with_visualization(model, image_embeddings, query, image_filenames, n=9):
    """
    Run image search and display results with visualizations
    """
    print(f"\nSearching for: {query}")
    matches, scores = find_matches(
        model=model,
        image_embeddings=image_embeddings,
        query=query,
        image_filenames=image_filenames,
        n=n
    )

    # Display image grid with normalized scores
    display_image_grid(matches, scores, query, f'results_{query[:20]}.png')

    # Plot both raw and normalized score distributions
    plot_similarity_distribution(scores, query, f'similarity_{query[:20]}.png')

    return matches, scores

if __name__ == "__main__":
    # Load model and prepare embeddings
    _, valid_df = make_train_valid_dfs()
    model, image_embeddings = get_image_embeddings(
        valid_df,
        "/content/best_model_epoch_1.pth"
    )

    # List of example queries
    queries = [
        "কক্সবাজারের সমুদ্র সৈকত",  # Cox's Bazar sea beach
        "ঢাকার রাস্তায় রিকশা",      # Rickshaw on Dhaka street
        "পদ্মা নদীর দৃশ্য",          # View of Padma River
        "সুন্দরবনের বাঘ",            # Tiger in Sundarbans
        "শাপলা ফুল",                 # Water lily flower
        "ঐতিহাসিক স্থাপনা",          # Historical architecture
    ]

    # Run search for each query
    results = {}
    for query in queries:
        matches, scores = run_image_search_with_visualization(
            model,
            image_embeddings,
            query,
            valid_df["image"].values
        )
        # Store results with proper type handling
        results[query] = {
            'matches': matches,
            'scores': scores,  # Keep original scores
            'normalized_scores': normalize_scores(np.array(scores, dtype=float))
        }

    # Create a summary visualization comparing raw and normalized scores
    plt.figure(figsize=(15, 6))

    x = np.arange(len(queries))
    width = 0.35

    # Calculate means with proper type conversion
    raw_scores = [np.mean(np.array(result['scores'], dtype=float)) for result in results.values()]
    norm_scores = [np.mean(result['normalized_scores']) for result in results.values()]

    plt.bar(x - width/2, raw_scores, width, label='Raw Scores')
    plt.bar(x + width/2, norm_scores, width, label='Normalized Scores')

    plt.xticks(x, [q[:15] + '...' for q in queries], rotation=45)
    plt.title('Comparison of Raw and Normalized Average Similarity Scores by Query')
    plt.xlabel('Query')
    plt.ylabel('Average Similarity Score')
    plt.legend()
    plt.tight_layout()
    plt.savefig('query_comparison.png', dpi=300, bbox_inches='tight')
    plt.close()

import shutil

# Install required libraries
!pip install huggingface_hub transformers

# Step 1: Configure Git credentials
!git config --global user.email "mansubatabassum9@gmailcom"
!git config --global user.name "Tabassum"

# Step 2: Define your Hugging Face token
import os
from huggingface_hub import login, HfApi, Repository

# Replace this with your actual token from huggingface.co/settings/tokens
HF_TOKEN = "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"  # Replace this with your actual token!

# Login to Hugging Face
try:
    login(token=HF_TOKEN)
    print("Successfully logged in to Hugging Face!")
except Exception as e:
    print(f"Login failed: {e}")
    raise

# Step 3: Repository setup
repo_name = "BanglaCLIP100"
repo_id = "Mansuba/BanglaCLIP100"
local_model_path = "/content/best_model_epoch_1.pth"

# Clean up existing repository
if os.path.exists(repo_name):
    shutil.rmtree(repo_name)
    print(f"Cleaned up existing {repo_name} directory")

# Initialize API
api = HfApi()

# Create or verify repository
try:
    api.create_repo(
        repo_id,
        private=False,
        exist_ok=True,
        token=HF_TOKEN
    )
    print(f"Repository {repo_id} is ready")
except Exception as e:
    print(f"Repository setup error: {e}")
    raise

# Clone repository
try:
    repo = Repository(
        local_dir=repo_name,
        clone_from=f"https://huggingface.co/{repo_id}",
        use_auth_token=HF_TOKEN,
        git_user="Tabassum",
        git_email="mansubatabassum9@gmailcom"
    )
    print("Repository cloned successfully")
except Exception as e:
    print(f"Cloning error: {e}")
    raise

# Step 4: Prepare model files
config = {
    "architectures": ["CLIPModel"],
    "model_type": "clip",
    "hidden_size": 768,
    "intermediate_size": 3072,
    "num_attention_heads": 12,
    "num_hidden_layers": 12
}

try:
    # Save config
    with open(os.path.join(repo_name, "config.json"), "w") as f:
        json.dump(config, f)
    print("Config file created")

    # Copy model file
    model_name = "banglaclip_model_epoch_10.pth"
    target_model_path = os.path.join(repo_name, model_name)
    shutil.copy(local_model_path, target_model_path)
    print("Model file copied")

    # Save tokenizer config
    tokenizer_config = {
        "model_max_length": 77,
        "padding_side": "right",
        "truncation_side": "right"
    }
    with open(os.path.join(repo_name, "tokenizer_config.json"), "w") as f:
        json.dump(tokenizer_config, f)
    print("Tokenizer config created")

    # Commit and push
    repo.git_add(".")
    repo.git_commit("Upload model and configs")
    repo.git_push()
    print("Successfully pushed to Hugging Face Hub!")

except Exception as e:
    print(f"Error during file operations: {e}")
    raise